### ISSUE TITLE
When using decrypt.py my output is not a tar file, but a decompressed binary file of the whole backup

### ISSUE THREAD

**Issue by northloopforensics** [joernheissler/ab-decrypt#2]
First of all, thank you for the great tool!  The code is clean and well organized.  I am not using it in the intended CLI design so feel free to close this issue if it is too far from what you created the tool for.

In decrypt.py, I have designated the in_stream variable using an absolute path to an ADB backup .ab file, and designated the out_stream variable to an absolute path .tar file.  Basically where your CLI code calls: 

>in_stream = in_stream(open(argv[1], "rb"))
&
>out_stream = out_stream(open(argv[2], "wb"))

I have replaced that with:

>with open(backupfile, "rb") as in_stream:
>    &emsp; with open(tarfile, "wb") as out_stream:
>     &emsp; &emsp;  decrypt_android_backup(in_stream, out_stream, get_password)

And it works great to decrypt the backup file.  

The output is a decrypted and decompressed binary file containing all of the backup contents. My goal is see the backup contents as individual logical files.

My .ab file header is normal - 
![Screenshot 2022-11-20 at 10 41 17 AM](https://user-images.githubusercontent.com/73806121/202914445-cfff943f-84a3-49be-9824-ee2237d92a7b.png)

My output .tar header looks like this - 
![Screenshot 2022-11-20 at 10 42 46 AM](https://user-images.githubusercontent.com/73806121/202914502-7bb6522a-0019-443d-8fcd-926e0f3222e3.png)

Inside the produced binary file I can see all of the decrypted, decompressed data.  I feel like I am missing a step to either produce the compressed .tar file or to get the decompressed directory structure.

Thanks for any advice you can offer.

**Comment by joernheissler** [comment]
Hello!
How is the output you're getting not a tar file? The file from your screen shot looks like tar to me.

Try `tar -tvf output.tar`

**Comment by northloopforensics** [comment]
My OS (Mac) wasn't able to open it as a tar.  I took the output to 7zip on Windows and it opens the tar without error.  Running the command you provided I get the same output and this error message:

cli.py backup.ab tar -tvf output.tar 

>Traceback (most recent call last):
 > File "cli.py", line 53, in <module>
  >  decrypt_android_backup(in_stream, out_stream, get_password)
 > File "/Users/nlc/Downloads/ab-decrypt-master/ab_decrypt/decryptor.py", line 300, in decrypt_android_backup
    writer.flush()
  >File "/Users/nlc/Downloads/ab-decrypt-master/ab_decrypt/decryptor.py", line 172, in flush
    self.stream.flush()
  File "/Users/nlc/Downloads/ab-decrypt-master/ab_decrypt/decryptor.py", line 135, in flush
    self.stream.write(self.unpadder.finalize())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cryptography/hazmat/primitives/padding.py", line 142, in finalize
    result = _byte_unpadding_check(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cryptography/hazmat/primitives/padding.py", line 89, in _byte_unpadding_check
    raise ValueError("Invalid padding bytes.")
ValueError: Invalid padding bytes.


I've run the Python tarfile library attempting to unpack the output and get a "tarfile.ReadError: unexpected end of data".

The thing is, this process works (as well as the 7zip did on Windows).  I need to test and see if I am actually missing data or if the padding error is just impacting the unpacking. 

I will let you know.  Thanks for the response.

**Comment by northloopforensics** [comment]
Sorry about the delay in getting back. It's been a busy December.  Over the holidays I have had some time to run some testing. Unfortunately, it has not been very productive.  The ValueError continued on large backups from Android 11 and above.  I think the issue is with the "-shared" designation on the ADB backups.  Which means the problem is with ADB and not ab-decrypt.

My work around is to create the backups without "-shared" and pulling storage areas on their own. This has worked well for me.

Thanks for your feedback and have a happy New Year.
